name:                emotive-conjugations
version:             0.1.0.2
github:              githubuser/emotive-conjugations
license:             AllRightsReserved
author:              Konstantine Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           2020 Konstantine Rybnikov

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/emotive-conjugations#readme>

dependencies:
- base
- aeson
- amazonka
- amazonka-core
- amazonka-s3
- binary
- bytestring
- conduit
- containers
- cookie
- cryptonite
- directory
- dhall
- either
- elm-bridge
- esqueleto
- fast-logger
- fsnotify
- hailgun
- http-client
- http-client-tls
- http-media
- http-types
- lens
- monoidal-containers
- monad-logger
- newtype
- neat-interpolation
- network-uri
- path-pieces
- persistent
- persistent-postgresql
- persistent-template
- pipes
- pipes-bytestring
- pipes-zlib
- pretty-simple
- random
- rio
- raw-strings-qq
- resourcet
- resource-pool
- safe
- servant
- servant-foreign
- servant-client
- servant-client-core
- servant-elm
- servant-server
- shake
- split
- string-class
- transformers
- text
- template-haskell
- time
- typed-process
- tz
- tzdata
- uuid
- unliftio
- uri-encode
- unordered-containers
- warc
- wai
- wai-app-static
- wai-middleware-static
- wai-extra
- warp
- warp-tls
- wreq

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - optparse-applicative

executables:
  conj:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - emotive-conjugations
    - optparse-applicative
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O

tests:
  emotive-conjugations-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - emotive-conjugations
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- StrictData
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- ViewPatterns
